name: localsend_app
description: An open source cross-platform alternative to AirDrop

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  collection: 1.16.0
  device_info_plus: 8.0.0
  dio: 4.0.6
  flutter:
    sdk: flutter
  network_info_plus: 3.0.1
  flutter_riverpod: 2.1.1
  freezed_annotation: 2.2.0
  json_annotation: 4.7.0
  shared_preferences: 2.0.15
  shelf: 1.4.0
  shelf_router: 1.1.3
  slang: 3.7.0
  slang_flutter: 3.7.0
  window_manager: 0.2.8

dev_dependencies:
  build_runner: 2.3.3
  flutter_gen_runner: 5.1.0+1
  flutter_lints: 2.0.1
  freezed: 2.3.2
  json_serializable: 6.5.4
  slang_build_runner: 3.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/