name: localsend_app
description: An open source cross-platform alternative to AirDrop

publish_to: 'none'

version: 1.3.0+11

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  basic_utils: 5.4.2
  collection: 1.16.0
  connectivity_plus: 3.0.2
  desktop_drop: 0.4.0
  device_info_plus: 8.0.0
  dio: 4.0.6
  file_picker: 5.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.13
  flutter_riverpod: 2.1.3
  freezed_annotation: 2.2.0
  image_gallery_saver: 1.7.1
  image_picker: 0.8.6
  json_annotation: 4.7.0
  network_info_plus: 3.0.1
  open_filex: 4.3.2
  package_info_plus: 3.0.2
  path_provider: 2.0.11
  permission_handler: 10.2.0
  responsive_builder: 0.4.3
  routerino: 0.2.0
  share_handler: 0.0.16
  shared_preferences: 2.0.15
  shelf: 1.4.0
  shelf_router: 1.1.3
  slang: 3.7.0
  slang_flutter: 3.7.0
  url_launcher: 6.1.7
  uuid: 3.0.7
  wechat_assets_picker: 8.3.0
  window_manager: 0.2.8

dev_dependencies:
  build_runner: 2.3.3
  flutter_gen_runner: 5.1.0+1
  flutter_lints: 2.0.1
  freezed: 2.3.2
  json_serializable: 6.5.4
  msix: 3.7.0
  slang_build_runner: 3.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - CHANGELOG.md

msix_config:
  display_name: LocalSend
  publisher_display_name: Tien Do Nam
  publisher: CN=0A8E9755-183F-4F0B-823F-1B8C991D7B97
  identity_name: 11157TienDoNam.LocalSend
  logo_path: assets\img\logo-512.png
  languages: en-us, de-de
