name: localsend_app
description: An open source cross-platform alternative to AirDrop

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  dio: 4.0.6
  flutter:
    sdk: flutter
  network_info_plus: 3.0.1
  shelf: 1.4.0
  shelf_router: 1.1.3

dev_dependencies:
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
