name: localsend_app
description: An open source cross-platform alternative to AirDrop
homepage: https://localsend.org/
publish_to: "none"

version: 1.15.1+50

environment:
  flutter: ">=3.13.0"
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_group_directory: 2.0.0
  basic_utils: 5.7.0
  collection: ^1.17.2 # allow newer versions, so it can compile with newer Flutter versions
  common:
    path: ../common
  connectivity_plus: 5.0.2
  dart_mappable: 4.2.2
  desktop_drop: 0.4.4
  device_apps: 2.2.0
  device_info_plus: 9.1.2
  dio: 5.4.3+1
  dynamic_color: 1.7.0
  file_picker: 8.0.0+1
  file_selector: 1.0.3
  flutter:
    sdk: flutter
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.19
  gal: 2.3.0
  image_picker: 1.0.8
  in_app_purchase: 3.1.13 # [FOSS_REMOVE]
  intl: ^0.18.0 # allow newer versions, so it can compile with newer Flutter versions
  legalize: ^1.2.2
  logging: 1.2.0
  # https://github.com/NightFeather0615/macos_dock_progress/issues/1
  # macos_dock_progress: 1.1.0
  mime: 1.0.4
  nanoid2: 2.0.1
  network_info_plus: 5.0.3
  open_filex: 4.4.0
  package_info_plus: 4.2.0
  pasteboard: ^0.2.0
  path: 1.8.3
  path_provider: 2.1.2
  permission_handler: 11.0.1
  pretty_qr_code: 3.3.0
  refena_flutter: 2.1.1
  refena_inspector_client: 2.0.0
  routerino: 0.8.0
  saf_stream: 0.4.0 # Saving files to SD card for Android <11
  screen_retriever: 0.1.9
  share_handler: 0.0.19
  share_handler_ios: 0.0.12 # Keep iOS <14 support
  shared_preferences: 2.2.3
  shared_preferences_platform_interface: any
  shared_storage: 0.8.1
  shelf: 1.4.1
  shelf_router: 1.1.4
  slang: 3.31.1
  slang_flutter: 3.31.0
  system_settings: 2.1.0
  tray_manager: 0.2.3
  uri_content: 2.2.0
  url_launcher: 6.2.4
  uuid: 3.0.7
  wakelock_plus: 1.1.4
  wechat_assets_picker: 8.8.1+1
  win32_registry: 1.1.2
  window_manager: 0.3.9
  windows_taskbar: 1.1.2
  yaru: 1.2.2

dev_dependencies:
  build_runner: 2.4.9
  dart_mappable_builder: 4.2.3
  flutter_gen_runner: 5.6.0
  flutter_lints: 3.0.1
  mockito: 5.4.4
  refena_inspector: 2.0.0
  slang_build_runner: 3.31.0
  slang_gpt: 0.10.2
  test: ^1.24.3

dependency_overrides:
  permission_handler_windows:
    # Remove windows support as it causes trouble with Windows 7
    # https://github.com/Baseflow/flutter-permission-handler/issues/1034
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/web/
    - assets/CHANGELOG.md

flutter_gen:
  line_length: 150
