name: localsend_app
description: An open source cross-platform alternative to AirDrop
homepage: https://localsend.org/
publish_to: "none"

version: 1.13.2+43

environment:
  flutter: ">=3.13.0"
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_group_directory: 2.0.0
  basic_utils: 5.7.0
  collection: ^1.17.2 # allow newer versions, so it can compile with newer Flutter versions
  common:
    path: ../common
  connectivity_plus: 5.0.2
  dart_mappable: 4.0.1
  desktop_drop: 0.4.4
  device_apps: 2.2.0
  device_info_plus: 9.1.1
  dio: 5.4.0
  dynamic_color: 1.6.8
  file_picker: 6.1.1
  file_selector: 1.0.1
  flutter:
    sdk: flutter
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.18+2
  gal: 2.1.4
  image_picker: 1.0.4
  in_app_purchase: 3.1.11 # [FOSS_REMOVE]
  intl: ^0.18.0 # allow newer versions, so it can compile with newer Flutter versions
  launch_at_startup: 0.2.2
  logging: 1.2.0
  mime: 1.0.4
  network_info_plus: 4.1.0
  open_filex: 4.3.4
  package_info_plus: 4.2.0
  pasteboard: ^0.2.0
  path: 1.8.3
  path_provider: 2.1.1
  permission_handler: 11.0.1
  pretty_qr_code: 3.0.0
  refena_flutter: 1.5.0
  refena_inspector_client: 1.2.0
  routerino: 0.8.0
  screen_retriever: 0.1.9
  share_handler: 0.0.19
  shared_preferences: 2.2.2
  shared_preferences_platform_interface: any
  shared_storage: 0.8.0
  shelf: 1.4.1
  shelf_router: 1.1.4
  slang: 3.26.1
  slang_flutter: 3.26.1
  system_settings: 2.1.0
  system_tray: 2.0.3
  tray_manager:
    # https://github.com/leanflutter/tray_manager/issues/30
    # The Linux tray manager is disabled for now
    git:
      url: https://github.com/Tienisto/tray_manager.git
      ref: b37f5e088e0f02c45a684ae41e9d2da2d5c596db
  url_launcher: 6.2.1
  uuid: 3.0.7
  wakelock_plus: 1.1.4
  wechat_assets_picker: 8.8.0
  window_manager: 0.3.7
  yaru: 1.2.0

dev_dependencies:
  build_runner: 2.4.7
  dart_mappable_builder: 4.0.1
  flutter_gen_runner: 5.3.2
  flutter_lints: 3.0.1
  mockito: 5.4.4
  msix: 3.16.7
  refena_inspector: 1.2.0
  slang_build_runner: 3.26.1
  slang_gpt: 0.10.0
  test: ^1.24.3

dependency_overrides:
  permission_handler_windows:
    # Remove windows support as it causes trouble with Windows 7
    # https://github.com/Baseflow/flutter-permission-handler/issues/1034
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/web/
    - assets/CHANGELOG.md

msix_config:
  display_name: LocalSend
  publisher_display_name: Tien Do Nam
  # Using third-party CA for now (see: https://github.com/localsend/localsend/issues/220)
  # publisher: CN=0A8E9755-183F-4F0B-823F-1B8C991D7B97
  identity_name: 11157TienDoNam.LocalSend
  logo_path: assets\img\logo-512.png
  architecture: x64
  languages: en, ar, bn, cs, da, de, el, es-ES, eu, fa, fr, he, hu, in, it, ja, ko, ne, nl, pl, pt-BR, ru, sv, th, tr, uk, vi, zh-CN, zh-HK, zh-TW

  # https://github.com/localsend/localsend/issues/398
  os_min_version: 10.0.19041.0

  startup_task:
    task_id: localsend
    enabled: false
    parameters: autostart
